# Generated by Django 2.1.7 on 2019-02-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Research_fellows', models.CharField(max_length=500)),
                ('Extension_weeks', models.IntegerField()),
                ('Project_completion', models.DateField()),
                ('Reason_of_extension', models.TextField()),
                ('Detail_remaining_work', models.TextField()),
                ('Progress_report', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bud_utilize', models.IntegerField()),
                ('Additional_bud', models.IntegerField()),
                ('Justify', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bud_utilize', models.IntegerField(blank=True)),
                ('Additional_bud', models.IntegerField(blank=True)),
                ('Justify', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research_fellow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bud_utilize', models.IntegerField()),
                ('Additional_bud', models.IntegerField()),
                ('Justify', models.TextField()),
            ],
        ),
    ]
